config/routes.rb
Rails.application.routes.draw do
  devise_for :mechanic_users
  resources :customers
  resources :sales
  resources :repairs
 #get 'home/index'
  root 'home#index'

  get 'home/repairs'
  get 'home/sales'
  get 'home/customers'
  get 'home/finance'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	
end

app/models/mechanic_user.rb
class MechanicUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #roles for mechanic, salesman and admin
  	class MechanicUser < ApplicationRecord
  		enum role: {guest: 0, mechanic:1 , salesman: 2, admin:3}
 	 end
end

app/models/repair.rb
class Repair < ApplicationRecord
	
end

app/models/sale.rb
class Sale < ApplicationRecord
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :car_license, :phone, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def repairs
  end

  def sales
  end

  def customers
  end

  def finance
  end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :set_repair, only: %i[ show edit update destroy ]

  # GET /repairs or /repairs.json
  def index
    @repairs = Repair.all
  end

  # GET /repairs/1 or /repairs/1.json
  def show
  end

  # GET /repairs/new
  def new
    @repair = Repair.new
  end

  # GET /repairs/1/edit
  def edit
  end

  # POST /repairs or /repairs.json
  def create
    @repair = Repair.new(repair_params)

    respond_to do |format|
      if @repair.save
        format.html { redirect_to @repair, notice: "Repair was successfully created." }
        format.json { render :show, status: :created, location: @repair }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repairs/1 or /repairs/1.json
  def update
    respond_to do |format|
      if @repair.update(repair_params)
        format.html { redirect_to @repair, notice: "Repair was successfully updated." }
        format.json { render :show, status: :ok, location: @repair }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1 or /repairs/1.json
  def destroy
    @repair.destroy
    respond_to do |format|
      format.html { redirect_to repairs_url, notice: "Repair was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair
      @repair = Repair.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def repair_params
      params.require(:repair).permit(:make, :model, :plate, :work_needed, :status)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:make, :model, :year, :features, :mileage, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :plate, class:"form-control", placeholder:"License Plate" %>
  </div>

  <div class="field form-group">
    
    <%= form.number_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
  <br>
  <div class="actions form-group">
    <%= form.submit class:'btn btn-dark' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="container">
<br/>
<h1>Editing Customer</h1>
<br/>
<%= render 'form', customer: @customer %>
<br/>
<%= link_to 'Show', @customer, class:'btn btn-dark' %> 
<%= link_to 'Back', customers_path, class:'btn btn-dark' %>
</div>

app/views/customers/index.html.erb
<h1>Customers</h1>

<table class="table table-striped table-bordered table-secondary table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Plate</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.plate %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer, class:"btn btn-light btn-sm" %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer), class:"btn btn-light btn-sm" %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-light btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path, class:"btn btn-dark" %>

app/views/customers/new.html.erb
<div class="container">
<br>
<h1>New Customer</h1>
<br>
<%= render 'form', customer: @customer %>

<br>
<%= link_to 'Back', customers_path, class:'btn btn-dark' %>
</div>

app/views/customers/show.html.erb
<div  class="jumbotron jumbotron-fluid">
  <div class="container" >
  <h1 class="display-4"> Customer: <%= @customer.first_name %> <%= @customer.last_name %> </h1>
 
  <p class="lead">
   <strong>Plate:</strong>
    <%= @customer.car_license %>
    <br>
    <strong>Phone:</strong>
    <%= @customer.phone %>
    <br>
    <strong>Email:</strong>
    <%= @customer.email %>
  </p>
  <hr class="my-4">

  <%= link_to 'Edit', edit_customer_path(@customer), class:"btn btn-dark" %> 
  <%= link_to 'Back', customers_path, class:"btn btn-dark" %>
</div>
</div>

app/views/home/_navigation.html.erb
<div class="container">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <!-- <a class="navbar-brand" > Panda Garage</a> -->
    <%= link_to 'Panda Garage', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

      <div class="navbar-nav">
      <!--  <%= link_to 'Home', root_path, class:"nav-link" %> -->
      
       <% if mechanic_user_signed_in? %>
          <%= link_to 'Repairs', repairs_path, class:"nav-link" %>
          <%= link_to 'Sales', sales_path, class:"nav-link" %>
          <%= link_to 'Customers', customers_path, class:"nav-link" %>
          <%= link_to 'Finance', home_finance_path, class:"nav-link" %>
        <% end %>
 
       <!-- filtering user by role 0 = guest see's only profile stuff, 1 = mechanic see's repairs and customers 2= sales see's customers finance and sales, 3= admin sees all -->
      <!-- this is the code that would be used if the roles were working -->
        <% if (mechanic_user_signed_in?) && (:role == 1) %>
          <%= link_to 'Repairs', repairs_path, class:"nav-link" %>
          <%= link_to 'Customers', customers_path, class:"nav-link" %>
        <% elseif (mechanic_user_signed_in?) && (self.runcheck(:role == 2)) %>
          <%= link_to 'Sales', sales_path, class:"nav-link" %>
          <%= link_to 'Customers', customers_path, class:"nav-link" %>
          <%= link_to 'Finance', home_finance_path, class:"nav-link" %>
        <% end %>
        <% if (mechanic_user_signed_in?) && (:role == 3) %>
          <%= link_to 'Repairs', repairs_path, class:"nav-link" %>
          <%= link_to 'Sales', sales_path, class:"nav-link" %>
          <%= link_to 'Customers', customers_path, class:"nav-link" %>
          <%= link_to 'Finance', home_finance_path, class:"nav-link" %>
        <% end %> 
      </div>  
      <!--not sure i remember how to push this to the right side of the nav bar gotta check later -->
      <div class="navbar-nav float-right">  

        <!-- login system links -->
        <% if mechanic_user_signed_in? %>
          <%= link_to 'Sign Out', destroy_mechanic_user_session_path, method: :delete, class:"nav-link" %>
          <%= link_to 'Profile', edit_mechanic_user_registration_path, class:"nav-link" %>
        <% else %>
          <%= link_to 'Sign Up', new_mechanic_user_registration_path, class:"nav-link" %>
          <%= link_to 'Sign In', new_mechanic_user_session_path, class:"nav-link" %>
        <% end %>

      </div>
        
      
    </div>
  </div>
</nav>
</div>

app/views/home/customers.html.erb
<h1> regular customers </h1>

app/views/home/finance.html.erb
<h1> aaaaaaaaaaaaaaaaaaaaaa </h1>

app/views/home/index.html.erb
<h1>insert fake garage website visuals here</h1>
<p></p>

app/views/home/sales.html.erb
<h1> sales </h1>

app/views/layouts/_notif.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong> 
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  <title>Garage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    
    <!-- calls to _nav in home for the navbar -->
    <%= render 'home/navigation' %> 
    <br>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/notif' %>
      <% end %>

      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    
  </body>
</html>

app/views/repairs/_form.html.erb
<%= form_with(model: repair) do |form| %>
  <% if repair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repair.errors.count, "error") %> prohibited this repair from being saved:</h2>

      <ul>
        <% repair.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    
    <%= form.text_field :make, class:"form-control", placeholder:"Make" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :model, class:"form-control", placeholder:"Model" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :plate, class:"form-control", placeholder:"Plate" %>
  </div>

  <div class="field form-group">

    <%= form.text_field :work_needed, class:"form-control", placeholder:"Work needed" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :status, class:"form-control", placeholder:"Status" %>
  </div>
  <br>
  <div class="actions form-group">
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/repairs/edit.html.erb
<div class="container">
<br/>
<h1>Editing Repair</h1>
<br/>
<%= render 'form', repair: @repair %>
<br/>
<%= link_to 'Show', @repair, class:'btn btn-dark' %> 
<%= link_to 'Back', repairs_path, class:'btn btn-dark' %>
</div>

app/views/repairs/index.html.erb
<h1>Repairs</h1>

<table class="table table-striped table-bordered table-secondary table-hover">
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Plate</th>
      <th>Work needed</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repairs.each do |repair| %>
      <tr>
        <td><%= repair.make %></td>
        <td><%= repair.model %></td>
        <td><%= repair.plate %></td>
        <td><%= repair.work_needed %></td>
        <td><%= repair.status %></td>
        <td><%= link_to 'Show', repair, class:"btn btn-light btn-sm" %></td>
        <td><%= link_to 'Edit', edit_repair_path(repair), class:"btn btn-light btn-sm" %></td>
        <td><%= link_to 'Destroy', repair, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-light btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repair', new_repair_path, class:"btn btn-dark" %>

app/views/repairs/new.html.erb
<div class="container">
<br>
<h1>New Repair</h1>
<br>
<%= render 'form', repair: @repair %>
<br>
<%= link_to 'Back', repairs_path, class:'btn btn-dark' %>
</div>

app/views/repairs/show.html.erb
<div  class="jumbotron jumbotron-fluid">
  <div class="container" >
  <h1 class="display-4"> Job: <%= @repair.work_needed %></h1>
 
  <p class="lead">
   <strong>Make:</strong>
   <%= @repair.make %>
   <br>
   <strong>Model:</strong>
   <%= @repair.model %>
   <br>
    <strong>Plate:</strong>
   <%= @repair.plate %>
   <br>
   <strong>Status:</strong>
    <%= @repair.status %>
    <br>
  </p>
  <hr class="my-4">
   <%= link_to 'Edit', edit_repair_path(@repair), class:"btn btn-dark" %> 
  <%= link_to 'Back', repairs_path, class:"btn btn-dark" %>
</div>
</div>

app/views/sales/_form.html.erb
<%= form_with(model: sale) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
        <% sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    
    <%= form.text_field :make, class:"form-control", placeholder:"Make" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :model, class:"form-control", placeholder:"Model" %>
  </div>

  <div class="field form-group">
    
    <%= form.number_field :year, class:"form-control", placeholder:"Year" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :features, class:"form-control", placeholder:"Features" %>
  </div>

  <div class="field form-group">
    
    <%= form.number_field :mileage, class:"form-control", placeholder:"Mileage" %>
  </div>

  <div class="field form-group">
    
    <%= form.number_field :price, class:"form-control", placeholder:"Price" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<div class="container">
<br/>
<h1>Editing Sale</h1>
<br/>
<%= render 'form', sale: @sale %>
<br/>
<%= link_to 'Show', @sale , class:'btn btn-dark'%> 
<%= link_to 'Back', sales_path, class:'btn btn-dark' %>
</div>

app/views/sales/index.html.erb
<h1>Sales</h1>

<table class="table table-bordered table-striped table-secondary table-hover">
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Features</th>
      <th>Mileage</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.make %></td>
        <td><%= sale.model %></td>
        <td><%= sale.year %></td>
        <td><%= sale.features %></td>
        <td><%= sale.mileage %></td>
        <td><%= sale.price %></td>
        <td><%= link_to 'Show', sale, class:"btn btn-light btn-sm" %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale), class:"btn btn-light btn-sm" %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-light btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path, class:"btn btn-dark" %>

app/views/sales/new.html.erb
<div class="container">
<br>
<h1>New Sale</h1>
<br>
<%= render 'form', sale: @sale %>
<br>
<%= link_to 'Back', sales_path, class:'btn btn-dark' %>
</div>

app/views/sales/show.html.erb
<div  class="jumbotron jumbotron-fluid">
  <div class="container" >
  <h1 class="display-4"> Car: <%= @sale.make %> <%= @sale.model %> </h1>
 
  <p class="lead">
  <strong>Year:</strong>
  <%= @sale.year %>
  <br>
  <strong>Features:</strong>
  <%= @sale.features %>
  <br>
  <strong>Mileage:</strong>
  <%= @sale.mileage %>
  <br>
  <strong>Price:</strong>
  <%= @sale.price %>
  <br>
  </p>
  <hr class="my-4">
   <%= link_to 'Edit', edit_sale_path(@sale), class:"btn btn-dark" %> 
<%= link_to 'Back', sales_path, class:"btn btn-dark" %>

</div>
</div>




  